name: Makefile CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: x86_64-unknown-none
        components: rust-src


    - name: Setup Netwide Assembler
      uses: ilammy/setup-nasm@v1

    - name: Install xorriso
      run: sudo apt-get update && sudo apt-get install -y xorriso

    - name: Verify xorriso installation
      run: xorriso -version

    - name: Install qemu
      run: sudo apt-get install qemu-system

    - name: Run build & test
      run: make test

    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: image.iso
    #    path: ./hexium_os-x86_64.iso
    #    if-no-files-found: error
